// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGZ_SccDyrvyMdkF3887SuJEgKNixEe1E',
    appId: '1:862467341877:web:48a741d14f73b0e3df7b7c',
    messagingSenderId: '862467341877',
    projectId: 'koupet-6c795',
    authDomain: 'koupet-6c795.firebaseapp.com',
    storageBucket: 'koupet-6c795.appspot.com',
    measurementId: 'G-SNB3NZGDEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJbttNr7ZbY_rl8GGqRQZGErJVW0j9nw',
    appId: '1:862467341877:android:0d7996f0670a3a4ddf7b7c',
    messagingSenderId: '862467341877',
    projectId: 'koupet-6c795',
    storageBucket: 'koupet-6c795.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcKO0K34lKY8j6OYuxtV5Dplg0Tdtc_hA',
    appId: '1:862467341877:ios:b7efa9ebffc0d749df7b7c',
    messagingSenderId: '862467341877',
    projectId: 'koupet-6c795',
    storageBucket: 'koupet-6c795.appspot.com',
    iosBundleId: 'com.example.softpati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcKO0K34lKY8j6OYuxtV5Dplg0Tdtc_hA',
    appId: '1:862467341877:ios:b7efa9ebffc0d749df7b7c',
    messagingSenderId: '862467341877',
    projectId: 'koupet-6c795',
    storageBucket: 'koupet-6c795.appspot.com',
    iosBundleId: 'com.example.softpati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGZ_SccDyrvyMdkF3887SuJEgKNixEe1E',
    appId: '1:862467341877:web:ff14615c3c3dace2df7b7c',
    messagingSenderId: '862467341877',
    projectId: 'koupet-6c795',
    authDomain: 'koupet-6c795.firebaseapp.com',
    storageBucket: 'koupet-6c795.appspot.com',
    measurementId: 'G-95420MNCPW',
  );
}
